using Normal.Realtime;
#region License
//------------------------------------------------------------------------------ -
// Normcore-ParameterBinder
// https://github.com/chetu3319/Normcore-ParameterBinder
//------------------------------------------------------------------------------ -
// MIT License
//
// Copyright (c) 2020 Chaitanya Shah
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files(the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions :
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//------------------------------------------------------------------------------ -
#endregion
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class NormalPrimaryDatatypeModel
{
  [RealtimeProperty(1, true, true)] public bool _boolProperty;
  [RealtimeProperty(2, false, true)] public float _floatProperty;
  [RealtimeProperty(3, true, true)] public Vector3 _vector3Property; 

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class NormalPrimaryDatatypeModel : RealtimeModel {
    public float floatProperty {
        get {
            return _floatProperty;
        }
        set {
            if (_floatProperty == value) return;
            _floatPropertyShouldWrite = true;
            _floatProperty = value;
            InvalidateUnreliableLength();
            FireFloatPropertyDidChange(value);
        }
    }
    
    public bool boolProperty {
        get {
            return _cache.LookForValueInCache(_boolProperty, entry => entry.boolPropertySet, entry => entry.boolProperty);
        }
        set {
            if (boolProperty == value) return;
            _cache.UpdateLocalCache(entry => { entry.boolPropertySet = true; entry.boolProperty = value; return entry; });
            InvalidateReliableLength();
            FireBoolPropertyDidChange(value);
        }
    }
    
    public UnityEngine.Vector3 vector3Property {
        get {
            return _cache.LookForValueInCache(_vector3Property, entry => entry.vector3PropertySet, entry => entry.vector3Property);
        }
        set {
            if (vector3Property == value) return;
            _cache.UpdateLocalCache(entry => { entry.vector3PropertySet = true; entry.vector3Property = value; return entry; });
            InvalidateReliableLength();
            FireVector3PropertyDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(NormalPrimaryDatatypeModel model, T value);
    public event PropertyChangedHandler<bool> boolPropertyDidChange;
    public event PropertyChangedHandler<float> floatPropertyDidChange;
    public event PropertyChangedHandler<UnityEngine.Vector3> vector3PropertyDidChange;
    
    private struct LocalCacheEntry {
        public bool boolPropertySet;
        public bool boolProperty;
        public bool vector3PropertySet;
        public UnityEngine.Vector3 vector3Property;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    private bool _floatPropertyShouldWrite;
    
    public enum PropertyID : uint {
        BoolProperty = 1,
        FloatProperty = 2,
        Vector3Property = 3,
    }
    
    public NormalPrimaryDatatypeModel() : this(null) {
    }
    
    public NormalPrimaryDatatypeModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireBoolPropertyDidChange(bool value) {
        try {
            boolPropertyDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireFloatPropertyDidChange(float value) {
        try {
            floatPropertyDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireVector3PropertyDidChange(UnityEngine.Vector3 value) {
        try {
            vector3PropertyDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteFloatLength((uint)PropertyID.FloatProperty);
            length += WriteStream.WriteVarint32Length((uint)PropertyID.BoolProperty, _boolProperty ? 1u : 0u);
            length += WriteStream.WriteBytesLength((uint)PropertyID.Vector3Property, WriteStream.Vector3ToBytesLength());
        } else if (context.unreliableChannel) {
            if (_floatPropertyShouldWrite) {
                length += WriteStream.WriteFloatLength((uint)PropertyID.FloatProperty);
            }
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.boolPropertySet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.BoolProperty, entry.boolProperty ? 1u : 0u);
            }
            if (entry.vector3PropertySet) {
                length += WriteStream.WriteBytesLength((uint)PropertyID.Vector3Property, WriteStream.Vector3ToBytesLength());
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteFloat((uint)PropertyID.FloatProperty, _floatProperty);
            _floatPropertyShouldWrite = false;
            stream.WriteVarint32((uint)PropertyID.BoolProperty, _boolProperty ? 1u : 0u);
            stream.WriteBytes((uint)PropertyID.Vector3Property, WriteStream.Vector3ToBytes(_vector3Property));
        } else if (context.unreliableChannel) {
            if (_floatPropertyShouldWrite) {
                _floatPropertyShouldWrite = false;
                stream.WriteFloat((uint)PropertyID.FloatProperty, _floatProperty);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateUnreliableLength();
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.boolPropertySet || entry.vector3PropertySet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.boolPropertySet) {
                stream.WriteVarint32((uint)PropertyID.BoolProperty, entry.boolProperty ? 1u : 0u);
                didWriteProperties = true;
            }
            if (entry.vector3PropertySet) {
                stream.WriteBytes((uint)PropertyID.Vector3Property, WriteStream.Vector3ToBytes(entry.vector3Property));
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.BoolProperty: {
                    bool previousValue = _boolProperty;
                    _boolProperty = (stream.ReadVarint32() != 0);
                    bool boolPropertyExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.boolPropertySet);
                    if (!boolPropertyExistsInChangeCache && _boolProperty != previousValue) {
                        FireBoolPropertyDidChange(_boolProperty);
                    }
                    break;
                }
                case (uint)PropertyID.FloatProperty: {
                    float previousValue = _floatProperty;
                    _floatProperty = stream.ReadFloat();
                    _floatPropertyShouldWrite = false;
                    if (_floatProperty != previousValue) {
                        FireFloatPropertyDidChange(_floatProperty);
                    }
                    break;
                }
                case (uint)PropertyID.Vector3Property: {
                    UnityEngine.Vector3 previousValue = _vector3Property;
                    _vector3Property = ReadStream.Vector3FromBytes(stream.ReadBytes());
                    bool vector3PropertyExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.vector3PropertySet);
                    if (!vector3PropertyExistsInChangeCache && _vector3Property != previousValue) {
                        FireVector3PropertyDidChange(_vector3Property);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _boolProperty = boolProperty;
        _vector3Property = vector3Property;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
