using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class NormcoreFloatModel
{
   [RealtimeProperty(1, true, true)] public float _floatProperty; 
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class NormcoreFloatModel : IModel {
    // Properties
    public float floatProperty {
        get { return _cache.LookForValueInCache(_floatProperty, entry => entry.floatPropertySet, entry => entry.floatProperty); }
        set { if (value == floatProperty) return; _cache.UpdateLocalCache(entry => { entry.floatPropertySet = true; entry.floatProperty = value; return entry; }); FireFloatPropertyDidChange(value); }
    }
    
    // Events
    public delegate void FloatPropertyDidChange(NormcoreFloatModel model, float value);
    public event         FloatPropertyDidChange floatPropertyDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool  floatPropertySet;
        public float floatProperty;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public NormcoreFloatModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireFloatPropertyDidChange(float value) {
        try {
            if (floatPropertyDidChange != null)
                floatPropertyDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        FloatProperty = 1,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _floatProperty = floatProperty;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteFloatLength((uint)PropertyID.FloatProperty);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.floatPropertySet)
                    length += WriteStream.WriteFloatLength((uint)PropertyID.FloatProperty);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteFloat((uint)PropertyID.FloatProperty, _floatProperty);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.floatPropertySet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.floatPropertySet)
                    stream.WriteFloat((uint)PropertyID.FloatProperty, entry.floatProperty);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool floatPropertyExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.floatPropertySet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.FloatProperty: {
                    float previousValue = _floatProperty;
                    
                    _floatProperty = stream.ReadFloat();
                    
                    if (!floatPropertyExistsInChangeCache && _floatProperty != previousValue)
                        FireFloatPropertyDidChange(_floatProperty);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
