using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class NormcoreBoolModel
{
    [RealtimeProperty(1,true,true)]
    public bool _property;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class NormcoreBoolModel : IModel {
    // Properties
    public bool property {
        get { return _cache.LookForValueInCache(_property, entry => entry.propertySet, entry => entry.property); }
        set { if (value == property) return; _cache.UpdateLocalCache(entry => { entry.propertySet = true; entry.property = value; return entry; }); FirePropertyDidChange(value); }
    }
    
    // Events
    public delegate void PropertyDidChange(NormcoreBoolModel model, bool value);
    public event         PropertyDidChange propertyDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool propertySet;
        public bool property;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public NormcoreBoolModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FirePropertyDidChange(bool value) {
        try {
            if (propertyDidChange != null)
                propertyDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        Property = 1,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _property = property;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Property, _property ? 1u : 0u);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.propertySet)
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.Property, entry.property ? 1u : 0u);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteVarint32((uint)PropertyID.Property, _property ? 1u : 0u);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.propertySet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.propertySet)
                    stream.WriteVarint32((uint)PropertyID.Property, entry.property ? 1u : 0u);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool propertyExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.propertySet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Property: {
                    bool previousValue = _property;
                    
                    _property = (stream.ReadVarint32() != 0);
                    
                    if (!propertyExistsInChangeCache && _property != previousValue)
                        FirePropertyDidChange(_property);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
